#
AllCops:
  Exclude:
    - '**/examples/**'
    - 'spec/**/*'
    - 'lib/fix_utf.rb'
    - 'lib/play.rb'
  #
  DisabledByDefault: false
  DisplayCopNames: true

Style/StringLiterals:
  # EnforcedStyle: double_quotes
  EnforcedStyle: single_quotes

Style/MultilineOperationIndentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false